version: '3.2'

services:
  esmaster01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /mnt/es:/usr/share/elasticsearch/data        
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms4256m -Xmx4256m"
      - node.master=true
      - node.data=true
      - node.name=esmaster01
      - cluster.initial_master_nodes=172.19.83.78


 

volumes:
  elasticsearch:
