version: '3.2'

services:
  esmaster01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /home/esdata_0:/usr/share/elasticsearch/data        
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:      
      - node.name=zi1
      # 是否可以成为master节点
      - node.master=false
      # 是否允许该节点存储数据,默认开启
      - node.data=true
      #- cluster.initial_master_nodes=172.19.83.78
      - discovery.seed_hosts=172.19.83.78
      - "ES_JAVA_OPTS=-Xms5256m -Xmx5256m"

      
      
      
      


 

volumes:
  elasticsearch:
