version: '3.2'

services:
  esmaster01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /home/esdata_0:/usr/share/elasticsearch/data        
    ports:
      - "9201:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms15256m -Xmx15256m"
      - "discovery.type=single-node"

      
      
      
      


 

volumes:
  elasticsearch:
