version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /mnt/es:/usr/share/elasticsearch/data
      - /home/esdata_1:/usr/share/elasticsearch/data1
      - /home/esdata_2:/usr/share/elasticsearch/data2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx23456m -Xms23456m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
      
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      #- type: bind
      #  source: ./logstash/config/pipelines.yml
      #  target: /usr/share/logstash/config/pipelines.yml
      #  read_only: true

      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - /data/input:/home

    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1256m -Xms1256m"
    networks:
      - elk
    depends_on:
      - elasticsearch


 

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
